import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
// To hide any of the documents add this on top of the file
//---
//sidebar_position: null
//---
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Frontend',
      items: [
        'Frontend/Reactivity',
        'Frontend/DOM Manipulation Architectures',
      ],
    },
     {
      type: 'category',
      label: 'Random Explorations',
      items: ['Random Explorations/Why-rails',  {
        type: 'category',
        label: 'Browser',
        items: [
          'Random Explorations/Browser/BrowserInternals',
          'Random Explorations/Browser/Rendering_Engine',
          'Random Explorations/Browser/Rust-rendering-engine-and-framework',
        ],
      }, {
        type: 'category',
        label: 'Databases',
        items: [
          'Random Explorations/Databases/basics',
          'Random Explorations/Databases/database-diagrams',
          'Random Explorations/Databases/practical-examples',
        ],
      },
      ],
    },
    {
      type: 'category',
      label: 'Thinking Patterns',
      items: ['Thinking Patterns/Segmentation-Differentiation'],
    },
    {
      type: 'category',
      label: 'Book Notes',
      items: ['Book Notes/Residues by Brain O\'Reilly'],
    },
    {
      type: 'category',
      label: 'To-Read Resources',
      items: ['To-Read Resources/May-2025'],
    },
    {
      type: 'category',
      label: 'Conf Talks Notes',
      items: ['Conf Talks Notes/an_introduction_to_residuality_theory'],
    },
  ],
};

export default sidebars;
